{ 
	"topmenu":"總分類",
	"language": "語言",
	"chinese": "國語",
	"taiwanese": "台語",
	"english":"英文",
    "japanese":"日文",
    "cantonese":"廣東",
    "children":"兒童",
    "all":"全部",
	"singer":"歌手",
	"male":"男歌手",
	"female":"女歌手",
	"group":"團體",
	"phosym":"聲符",
	"bopomofo": "注音",
	"alpha":"拼音",
	"bopomofo_list":"ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦ",
	"1 chars":"一字部",
	"2 chars":"二字部",
	"3 chars":"三字部",
	"4 chars":"四字部",
	"5 chars":"五字部",
	"6 chars":"六字部",
	"7 chars":"七字部",
	"8 chars":"八字部",
	"9 chars":"九字部",
	"10 chars":"十字以上"
}


